# File: platoon_simulations/params/robots.yaml

robot1:
  robot_model: waffle
  robot_prefix: waffle1
  x_pose: 2.0
  y_pose: 0.0

robot2:
  robot_model: waffle
  robot_prefix: waffle2
  x_pose: 1.0
  y_pose: 0.0

# robot3:
#   robot_model: waffle
#   robot_prefix: waffle3
#   x_pose: -1.0
#   y_pose: 0.0